-- 코드를 입력하세요
SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE * (100-C.DISCOUNT_RATE) * 30 / 100 as FEE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE A.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE like '30일%'
AND A.CAR_TYPE in ('세단','SUV')
AND A.DAILY_FEE * (100-C.DISCOUNT_RATE) * 30 / 100 >=500000
AND A.DAILY_FEE * (100-C.DISCOUNT_RATE) * 30 / 100 < 2000000
AND NOT EXISTS(
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    WHERE B.CAR_ID = A.CAR_ID
    AND B.START_DATE <= TO_DATE('2022-11-30', 'yyyy-mm-dd')
    AND B.END_DATE   >= TO_DATE('2022-11-01', 'yyyy-mm-dd') 
)
order by 3 desc, 2 asc, 1 desc;

