-- 코드를 입력하세요
SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE,'yyyy-mm-dd') as REVIEW_DATE
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
AND A.MEMBER_ID in (

    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    order by COUNT(*) desc
    FETCH FIRST 1 rows only
)
order by 3,2;
