-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT A, FOOD_ORDER B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
AND DATE_FORMAT(B.PRODUCE_DATE,'%Y-%m') = '2022-05'
group by A.PRODUCT_ID,A.PRODUCT_NAME
order by TOTAL_SALES desc, A.PRODUCT_ID;

